### ISSUE TITLE
Broken compiler link in mdl 6.1.0?

### ISSUE THREAD

**Issue by wintvelt** [debois/elm-mdl#123]
After upgrading to 6.1.0, I got the following error when recompiling webpack.

> Module build failed: Error: Compiler process exited with error Compilation failed
> Success! Compiled 54 modules.
> elm-make: elm-stuff/build-artifacts/0.17.0/debois/elm-mdl/6.1.0/Material-Options-Internal.elmo: openFile: does not exist (No such file or directory)

**Comment by debois** [comment]
Try removing `elm-stuff`, then recompile?

**Comment by wintvelt** [comment]
Thanks for the quick reply, it worked! Back in business 😄

**Comment by debois** [comment]
Very welcome!
